// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDombTVSbVnOQqR42LZbaNZxWvA-HPNg-c',
    appId: '1:21876434470:web:2655fb1ef41f07893b68e7',
    messagingSenderId: '21876434470',
    projectId: 'mygamestrack',
    authDomain: 'mygamestrack.firebaseapp.com',
    storageBucket: 'mygamestrack.firebasestorage.app',
    measurementId: 'G-L1W402EV36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATz71xUPtN4cT7ziAIq8YCLFt8MEGSePs',
    appId: '1:21876434470:android:cc7dda08f8475c2a3b68e7',
    messagingSenderId: '21876434470',
    projectId: 'mygamestrack',
    storageBucket: 'mygamestrack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfSmDCPCbmv10z7NHimVU-9bFzOtdAhTo',
    appId: '1:21876434470:ios:8f5560141df3f5c13b68e7',
    messagingSenderId: '21876434470',
    projectId: 'mygamestrack',
    storageBucket: 'mygamestrack.firebasestorage.app',
    androidClientId: '21876434470-cjlkufau8ij03l64hj9srfcjsujijdul.apps.googleusercontent.com',
    iosClientId: '21876434470-41k9b695q8l8ctikr1gs4pt98r4q0a8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfSmDCPCbmv10z7NHimVU-9bFzOtdAhTo',
    appId: '1:21876434470:ios:8f5560141df3f5c13b68e7',
    messagingSenderId: '21876434470',
    projectId: 'mygamestrack',
    storageBucket: 'mygamestrack.firebasestorage.app',
    androidClientId: '21876434470-cjlkufau8ij03l64hj9srfcjsujijdul.apps.googleusercontent.com',
    iosClientId: '21876434470-41k9b695q8l8ctikr1gs4pt98r4q0a8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-fjLcVPznGkL21-vP_3_8H8Nyyrawuk8',
    appId: '1:21876434470:web:70327b25fc1f06503b68e7',
    messagingSenderId: '21876434470',
    projectId: 'mygamestrack',
    authDomain: 'mygamestrack.firebaseapp.com',
    storageBucket: 'mygamestrack.firebasestorage.app',
    measurementId: 'G-4CPN1Y7W2L',
  );

}